# fly.toml app configuration file
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

# enter here the same name as the one you used to create your app
# on the fly.io site
app = 'backend-fastapi-flyio'
primary_region = 'cdg'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    grace_period = "1s"
    interval = "30s"
    method = "GET"
    timeout = "1s"
    path = "/up"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
