[project]
name = "backend-flyio"
version = "0.1.0"
description = "How to host a FastAPI app on Fly.io"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "uvicorn",
    "fastapi[standard]>=0.115.12",
]
